package com.dayofpi.sbw_main.item.registry;

import com.dayofpi.sbw_main.Main;
import com.dayofpi.sbw_main.block.registry.ModBlocks;
import com.dayofpi.sbw_main.entity.registry.ModEntities;
import com.dayofpi.sbw_main.entity.types.ModBoatEntity;
import com.dayofpi.sbw_main.item.types.*;
import com.dayofpi.sbw_main.world.registry.ModFluids;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;
import net.minecraft.util.registry.Registry;


public class ModItems {
    public static final ArmorMaterial GREEN_SHELL_ARMOR_MATERIAL = new GreenShellArmorMaterial();
    public static final ArmorMaterial RED_SHELL_ARMOR_MATERIAL = new RedShellArmorMaterial();
    public static final ArmorMaterial BUZZY_ARMOR_MATERIAL = new BuzzyArmorMaterial();
    public static final ArmorMaterial JUMP_ARMOR_MATERIAL = new JumpArmorMaterial();

    public static final Item POWER_STAR = new PowerStarItem(new FabricItemSettings().rarity(Rarity.RARE));
    public static final Item POWER_DUST = new Item(new FabricItemSettings());
    public static final Item YOSHI_FRUIT = new Item(new FabricItemSettings().food(FoodComponents.YOSHI_FRUIT).group(CreativeTabs.ITEM_GROUP));
    public static final Item YOSHI_COOKIE = new Item(new FabricItemSettings().food(FoodComponents.YOSHI_COOKIE).group(CreativeTabs.ITEM_GROUP));
    public static final Item TURNIP = new TurnipItem(new FabricItemSettings().maxCount(16).group(CreativeTabs.ITEM_GROUP));
    public static final Item HAMMER = new HammerItem(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).maxDamage(50));
    public static final Item BOMB = new BombItem(new FabricItemSettings().maxCount(16).group(CreativeTabs.ITEM_GROUP));
    public static final Item SUPER_MUSHROOM = new Item(new FabricItemSettings().food(FoodComponents.SUPER_MUSHROOM).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item GOLDEN_MUSHROOM = new Item(new FabricItemSettings().food(FoodComponents.GOLDEN_MUSHROOM).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item ONE_UP = new OneUpItem(new FabricItemSettings().food(FoodComponents.ONE_UP).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item POISON_MUSHROOM = new Item(new FabricItemSettings().food(FoodComponents.POISON_MUSHROOM).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item FIRE_FLOWER = new FireFlowerItem(new FabricItemSettings().maxDamage(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item ICE_FLOWER = new IceFlowerItem(new FabricItemSettings().maxDamage(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item SUPER_STAR = new SuperStarItem(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).rarity(Rarity.RARE));
    public static final Item COIN = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item RAW_BRONZE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BRONZE_INGOT = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item TROOP_HIDE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item CLOUD_PUFF = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item SPIKE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BUZZY_SHELL_PIECE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item GREEN_SHELL = new ArmorItem(GREEN_SHELL_ARMOR_MATERIAL, EquipmentSlot.HEAD, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item RED_SHELL = new ArmorItem(RED_SHELL_ARMOR_MATERIAL, EquipmentSlot.HEAD, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BUZZY_SHELL = new ArmorItem(BUZZY_ARMOR_MATERIAL, EquipmentSlot.HEAD, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item JUMP_BOOTS = new ArmorItem(JUMP_ARMOR_MATERIAL, EquipmentSlot.FEET, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BOTTLE_O_GHOST = new Item(new FabricItemSettings().recipeRemainder(Items.GLASS_BOTTLE).group(CreativeTabs.ITEM_GROUP));
    public static final Item GREEN_MUSHROOM_ON_A_STICK = new OnAStickItem<>(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).maxDamage(25), ModEntities.BUZZY_BEETLE, 2);
    public static final Item AMANITA_BOAT = new ModBoatItem(ModBoatEntity.Type.AMANITA, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).maxCount(1));
    public static final Item POISON_BUCKET = new BucketItem(ModFluids.STILL_POISON, new FabricItemSettings().recipeRemainder(Items.BUCKET).maxCount(1).group(CreativeTabs.ITEM_GROUP));
    public static final Item MOO_MOO_SPAWN_EGG = new SpawnEggItem(ModEntities.MOO_MOO, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item GOOMBA_SPAWN_EGG = new SpawnEggItem(ModEntities.GOOMBA, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item PARAGOOMBA_SPAWN_EGG = new SpawnEggItem(ModEntities.PARAGOOMBA, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BOB_OMB_SPAWN_EGG = new SpawnEggItem(ModEntities.BOB_OMB, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BOO_SPAWN_EGG = new SpawnEggItem(ModEntities.BOO, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item HAMMER_BRO_SPAWN_EGG = new SpawnEggItem(ModEntities.HAMMER_BRO, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BUZZY_BEETLE_SPAWN_EGG = new SpawnEggItem(ModEntities.BUZZY_BEETLE, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item SPIKE_TOP_SPAWN_EGG = new SpawnEggItem(ModEntities.SPIKE_TOP, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item NIPPER_PLANT_SPAWN_EGG = new SpawnEggItem(ModEntities.NIPPER_PLANT, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item STINGBY_SPAWN_EGG = new SpawnEggItem(ModEntities.STINGBY, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item ROTTEN_MUSHROOM_SPAWN_EGG = new SpawnEggItem(ModEntities.ROTTEN_MUSHROOM, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));

    public static void registerItems() {
        registerBlockItems();
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "power_star"), POWER_STAR);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "power_dust"), POWER_DUST);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yoshi_fruit"), YOSHI_FRUIT);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yoshi_cookie"), YOSHI_COOKIE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "turnip"), TURNIP);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hammer"), HAMMER);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bomb"), BOMB);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_shell"), GREEN_SHELL);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "red_shell"), RED_SHELL);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "buzzy_shell"), BUZZY_SHELL);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "jump_boots"), JUMP_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "super_mushroom"), SUPER_MUSHROOM);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_mushroom"), GOLDEN_MUSHROOM);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "one_up"), ONE_UP);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "poison_mushroom"), POISON_MUSHROOM);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fire_flower"), FIRE_FLOWER);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "ice_flower"), ICE_FLOWER);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "super_star"), SUPER_STAR);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coin"), COIN);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "raw_bronze"), RAW_BRONZE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_ingot"), BRONZE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "troop_hide"), TROOP_HIDE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cloud_puff"), CLOUD_PUFF);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spike"), SPIKE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "buzzy_shell_piece"), BUZZY_SHELL_PIECE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_mushroom_on_a_stick"), GREEN_MUSHROOM_ON_A_STICK);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_boat"), AMANITA_BOAT);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bottle_o_ghost"), BOTTLE_O_GHOST);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "poison_bucket"), POISON_BUCKET);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/moo_moo"), MOO_MOO_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/goomba"), GOOMBA_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/paragoomba"), PARAGOOMBA_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/bob_omb"), BOB_OMB_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/boo"), BOO_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/hammer_bro"), HAMMER_BRO_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/buzzy_beetle"), BUZZY_BEETLE_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/spike_top"), SPIKE_TOP_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/nipper_plant"), NIPPER_PLANT_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/stingby"), STINGBY_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/rotten_mushroom"), ROTTEN_MUSHROOM_SPAWN_EGG);
    }

    public static void registerBlockItems() {
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "warp_frame"), new BlockItem(ModBlocks.WARP_FRAME, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "warp_pipe"), new BlockItem(ModBlocks.WARP_PIPE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "warp_pipe_body"), new BlockItem(ModBlocks.WARP_PIPE_BODY, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "girder"), new BlockItem(ModBlocks.GIRDER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spike_trap"), new BlockItem(ModBlocks.SPIKE_TRAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "empty_block"), new BlockItem(ModBlocks.EMPTY_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "question_block"), new BlockItem(ModBlocks.QUESTION_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).rarity(Rarity.UNCOMMON)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coin_block"), new BlockItem(ModBlocks.COIN_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).rarity(Rarity.UNCOMMON)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fake_block"), new BlockItem(ModBlocks.FAKE_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).rarity(Rarity.UNCOMMON)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "jump_block"), new BlockItem(ModBlocks.JUMP_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "redstone_trampoline"), new BlockItem(ModBlocks.REDSTONE_TRAMPOLINE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "trampoline"), new BlockItem(ModBlocks.TRAMPOLINE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "stone_torch"), new BlockItem(ModBlocks.STONE_TORCH, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "boo_lantern"), new BlockItem(ModBlocks.BOO_LANTERN, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "donut_block"), new BlockItem(ModBlocks.DONUT_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_grass"), new BlockItem(ModBlocks.TOADSTOOL_GRASS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_turf"), new BlockItem(ModBlocks.TOADSTOOL_TURF, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_soil"), new BlockItem(ModBlocks.TOADSTOOL_SOIL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coarse_toadstool_soil"), new BlockItem(ModBlocks.COARSE_TOADSTOOL_SOIL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_farmland"), new BlockItem(ModBlocks.TOADSTOOL_FARMLAND, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_path"), new BlockItem(ModBlocks.TOADSTOOL_PATH, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gritzy_sand"), new BlockItem(ModBlocks.GRITZY_SAND, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gritzy_sandstone"), new BlockItem(ModBlocks.GRITZY_SANDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "smooth_gritzy_sandstone"), new BlockItem(ModBlocks.SMOOTH_GRITZY_SANDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "seastone"), new BlockItem(ModBlocks.SEASTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "seastone_bricks"), new BlockItem(ModBlocks.SEASTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "seastone_brick_slab"), new BlockItem(ModBlocks.SEASTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "seastone_brick_stairs"), new BlockItem(ModBlocks.SEASTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "strawberry_coral_block"), new BlockItem(ModBlocks.STRAWBERRY_CORAL_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "happy_cloud"), new BlockItem(ModBlocks.HAPPY_CLOUD, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cloud_block"), new BlockItem(ModBlocks.CLOUD_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cloud_slab"), new BlockItem(ModBlocks.CLOUD_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate"), new BlockItem(ModBlocks.VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_bricks"), new BlockItem(ModBlocks.VANILLATE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_tiles"), new BlockItem(ModBlocks.VANILLATE_TILES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_crumble"), new BlockItem(ModBlocks.VANILLATE_CRUMBLE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_slab"), new BlockItem(ModBlocks.VANILLATE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_stairs"), new BlockItem(ModBlocks.VANILLATE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_brick_slab"), new BlockItem(ModBlocks.VANILLATE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_brick_stairs"), new BlockItem(ModBlocks.VANILLATE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "topped_vanillate"), new BlockItem(ModBlocks.TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coal_topped_vanillate"), new BlockItem(ModBlocks.COAL_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "iron_topped_vanillate"), new BlockItem(ModBlocks.IRON_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gold_topped_vanillate"), new BlockItem(ModBlocks.GOLD_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_ore"), new BlockItem(ModBlocks.BRONZE_ORE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amethyst_ore"), new BlockItem(ModBlocks.AMETHYST_ORE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate"), new BlockItem(ModBlocks.FROSTY_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_bricks"), new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_tiles"), new BlockItem(ModBlocks.FROSTY_VANILLATE_TILES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_crumble"), new BlockItem(ModBlocks.FROSTY_VANILLATE_CRUMBLE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_slab"), new BlockItem(ModBlocks.FROSTY_VANILLATE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_stairs"), new BlockItem(ModBlocks.FROSTY_VANILLATE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_brick_slab"), new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_vanillate_brick_stairs"), new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_topped_vanillate"), new BlockItem(ModBlocks.FROSTY_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "frosty_topped_vanillate_ore"), new BlockItem(ModBlocks.FROSTY_TOPPED_VANILLATE_ORE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        // Bronze
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "white_bronze"), new BlockItem(ModBlocks.WHITE_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "orange_bronze"), new BlockItem(ModBlocks.ORANGE_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "magenta_bronze"), new BlockItem(ModBlocks.MAGENTA_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "light_blue_bronze"), new BlockItem(ModBlocks.LIGHT_BLUE_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_bronze"), new BlockItem(ModBlocks.YELLOW_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "lime_bronze"), new BlockItem(ModBlocks.LIME_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_bronze"), new BlockItem(ModBlocks.PINK_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gray_bronze"), new BlockItem(ModBlocks.GRAY_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "light_gray_bronze"), new BlockItem(ModBlocks.LIGHT_GRAY_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cyan_bronze"), new BlockItem(ModBlocks.CYAN_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "purple_bronze"), new BlockItem(ModBlocks.PURPLE_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "blue_bronze"), new BlockItem(ModBlocks.BLUE_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "brown_bronze"), new BlockItem(ModBlocks.BROWN_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_bronze"), new BlockItem(ModBlocks.GREEN_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "red_bronze"), new BlockItem(ModBlocks.RED_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "black_bronze"), new BlockItem(ModBlocks.BLACK_BRONZE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "raw_bronze_block"), new BlockItem(ModBlocks.RAW_BRONZE_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_block"), new BlockItem(ModBlocks.BRONZE_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_slab"), new BlockItem(ModBlocks.BRONZE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_stairs"), new BlockItem(ModBlocks.BRONZE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone"), new BlockItem(ModBlocks.TOADSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "smooth_toadstone"), new BlockItem(ModBlocks.SMOOTH_TOADSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "chiseled_toadstone"), new BlockItem(ModBlocks.CHISELED_TOADSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_bricks"), new BlockItem(ModBlocks.TOADSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_slab"), new BlockItem(ModBlocks.TOADSTONE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_stairs"), new BlockItem(ModBlocks.TOADSTONE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_wall"), new BlockItem(ModBlocks.TOADSTONE_WALL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_brick_slab"), new BlockItem(ModBlocks.TOADSTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_brick_stairs"), new BlockItem(ModBlocks.TOADSTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_brick_wall"), new BlockItem(ModBlocks.TOADSTONE_BRICK_WALL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone"), new BlockItem(ModBlocks.GLOOMSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "smooth_gloomstone"), new BlockItem(ModBlocks.SMOOTH_GLOOMSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "chiseled_gloomstone"), new BlockItem(ModBlocks.CHISELED_GLOOMSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_bricks"), new BlockItem(ModBlocks.GLOOMSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_slab"), new BlockItem(ModBlocks.GLOOMSTONE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_stairs"), new BlockItem(ModBlocks.GLOOMSTONE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_wall"), new BlockItem(ModBlocks.GLOOMSTONE_WALL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_brick_slab"), new BlockItem(ModBlocks.GLOOMSTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_brick_stairs"), new BlockItem(ModBlocks.GLOOMSTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_brick_wall"), new BlockItem(ModBlocks.GLOOMSTONE_BRICK_WALL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone"), new BlockItem(ModBlocks.HARDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "polished_hardstone"), new BlockItem(ModBlocks.POLISHED_HARDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "chiseled_hardstone"), new BlockItem(ModBlocks.CHISELED_HARDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_pillar"), new BlockItem(ModBlocks.HARDSTONE_PILLAR, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_bricks"), new BlockItem(ModBlocks.HARDSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cracked_hardstone_bricks"), new BlockItem(ModBlocks.CRACKED_HARDSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "polished_hardstone_slab"), new BlockItem(ModBlocks.POLISHED_HARDSTONE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "polished_hardstone_stairs"), new BlockItem(ModBlocks.POLISHED_HARDSTONE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_brick_slab"), new BlockItem(ModBlocks.HARDSTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_brick_stairs"), new BlockItem(ModBlocks.HARDSTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_bricks"), new BlockItem(ModBlocks.GOLDEN_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_brick_slab"), new BlockItem(ModBlocks.GOLDEN_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_brick_stairs"), new BlockItem(ModBlocks.GOLDEN_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "crystal_bricks"), new BlockItem(ModBlocks.CRYSTAL_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "crystal_brick_slab"), new BlockItem(ModBlocks.CRYSTAL_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "crystal_brick_stairs"), new BlockItem(ModBlocks.CRYSTAL_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_log"), new BlockItem(ModBlocks.AMANITA_LOG, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_wood"), new BlockItem(ModBlocks.AMANITA_WOOD, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "stripped_amanita_log"), new BlockItem(ModBlocks.STRIPPED_AMANITA_LOG, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "stripped_amanita_wood"), new BlockItem(ModBlocks.STRIPPED_AMANITA_WOOD, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_planks"), new BlockItem(ModBlocks.AMANITA_PLANKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_slab"), new BlockItem(ModBlocks.AMANITA_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_stairs"), new BlockItem(ModBlocks.AMANITA_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_fence"), new BlockItem(ModBlocks.AMANITA_FENCE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_fence_gate"), new BlockItem(ModBlocks.AMANITA_FENCE_GATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_door"), new BlockItem(ModBlocks.AMANITA_DOOR, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_trapdoor"), new BlockItem(ModBlocks.AMANITA_TRAPDOOR, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_button"), new BlockItem(ModBlocks.AMANITA_BUTTON, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_pressure_plate"), new BlockItem(ModBlocks.AMANITA_PRESSURE_PLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_sign"), new SignItem(new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).maxCount(16), ModBlocks.AMANITA_SIGN, ModBlocks.AMANITA_WALL_SIGN));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_leaves"), new BlockItem(ModBlocks.AMANITA_LEAVES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fruiting_amanita_leaves"), new BlockItem(ModBlocks.FRUITING_AMANITA_LEAVES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "beanstalk_block"), new BlockItem(ModBlocks.BEANSTALK_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "mushroom_stem"), new BlockItem(ModBlocks.MUSHROOM_STEM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "brown_mushroom_cap"), new BlockItem(ModBlocks.BROWN_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "red_mushroom_cap"), new BlockItem(ModBlocks.RED_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_mushroom_cap"), new BlockItem(ModBlocks.GREEN_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_mushroom_cap"), new BlockItem(ModBlocks.PINK_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_mushroom_cap"), new BlockItem(ModBlocks.YELLOW_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "orange_mushroom_cap"), new BlockItem(ModBlocks.ORANGE_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "purple_mushroom_cap"), new BlockItem(ModBlocks.PURPLE_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_sapling"), new BlockItem(ModBlocks.AMANITA_SAPLING, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_carpet"), new BlockItem(ModBlocks.AMANITA_CARPET, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_flowerbed"), new BlockItem(ModBlocks.YELLOW_FLOWERBED, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "white_flowerbed"), new BlockItem(ModBlocks.WHITE_FLOWERBED, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "blue_songflower"), new BlockItem(ModBlocks.BLUE_SONGFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_songflower"), new BlockItem(ModBlocks.PINK_SONGFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_songflower"), new BlockItem(ModBlocks.YELLOW_SONGFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pawflower"), new BlockItem(ModBlocks.PAWFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fire_tulip"), new BlockItem(ModBlocks.FIRE_TULIP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "horsetail"), new BlockItem(ModBlocks.HORSETAIL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bush"), new BlockItem(ModBlocks.BUSH, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cave_mushrooms"), new BlockItem(ModBlocks.CAVE_MUSHROOMS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vegetable"), new BlockItem(ModBlocks.VEGETABLE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "muncher"), new BlockItem(ModBlocks.MUNCHER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "beanstalk"), new BlockItem(ModBlocks.BEANSTALK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "budding_beanstalk"), new BlockItem(ModBlocks.BUDDING_BEANSTALK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "piranha_lily"), new PiranhaLilyItem(ModBlocks.PIRANHA_LILY, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "strawberry_coral"), new BlockItem(ModBlocks.STRAWBERRY_CORAL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "icicle"), new BlockItem(ModBlocks.ICICLE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_mushroom"), new BlockItem(ModBlocks.GREEN_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_mushroom"), new BlockItem(ModBlocks.PINK_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_mushroom"), new BlockItem(ModBlocks.YELLOW_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "orange_mushroom"), new BlockItem(ModBlocks.ORANGE_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "purple_mushroom"), new BlockItem(ModBlocks.PURPLE_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        }
}
