package com.dayofpi.super_block_world.registry;

import com.dayofpi.super_block_world.Main;
import com.dayofpi.super_block_world.audio.Sounds;
import com.dayofpi.super_block_world.util.PowerUp;
import com.dayofpi.super_block_world.common.entities.misc.StampEntity;
import com.dayofpi.super_block_world.common.items.*;
import com.dayofpi.super_block_world.common.materials.*;
import com.dayofpi.super_block_world.util.EnumAddons;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.registry.CompostingChanceRegistry;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;
import net.minecraft.util.registry.Registry;

public class ModItems {
    public static final Item RAW_BRONZE = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item BRONZE_INGOT = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item CERISE = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item COIN = new BlockItem(ModBlocks.COIN, new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item STAR_COIN = new BlockItem(ModBlocks.STAR_COIN, new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item STELLAR_SHARD = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item YELLOW_STAR_BIT = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item GREEN_STAR_BIT = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item BLUE_STAR_BIT = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item PURPLE_STAR_BIT = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item SMILEY_SUNFLOWER_SEED = new BlockItem(ModBlocks.SMILEY_SUNFLOWER_SEED, new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item SPINDRIFT_BLOSSOM = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item KART_TIRE = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item SPIKE = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item TROOP_HIDE = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item CLOUD_PUFF = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item SUBCON_THREAD = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item GOOP_BALL = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item BLACK_PAINT = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item FUZZBALL = new BlockItem(ModBlocks.FUZZBALL, new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item BUZZY_SHELL_PIECE = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item POISON_BUCKET = new BucketItem(ModFluids.POISON, new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item BOTTLED_GHOST = new Item(new FabricItemSettings().recipeRemainder(Items.GLASS_BOTTLE).group(Main.ITEM_GROUP));
    public static final Item KEY = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item SKELETON_KEY = new SkeletonKeyItem(new FabricItemSettings().rarity(Rarity.EPIC));
    public static final Item POWER_STAR = new PowerStarItem(ModBlocks.POWER_STAR, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.RARE));
    public static final Item ZTAR = new PowerStarItem(ModBlocks.ZTAR, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.EPIC));
    public static final Item POWER_SHARD = new Item(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item YOSHI_FRUIT = new Item(new FabricItemSettings().food(new FoodComponent.Builder().hunger(3).saturationModifier(0.3F).build()).group(Main.ITEM_GROUP));
    public static final Item YOSHI_COOKIE = new Item(new FabricItemSettings().food(new FoodComponent.Builder().hunger(5).saturationModifier(0.6F).build()).group(Main.ITEM_GROUP));
    public static final Item HORSETAIL_TART = new Item(new FabricItemSettings().food(new FoodComponent.Builder().hunger(5).saturationModifier(0.5F).build()).group(Main.ITEM_GROUP));
    public static final Item RAW_DINO = new Item(new FabricItemSettings().food(FoodComponents.BEEF).group(Main.ITEM_GROUP));
    public static final Item COOKED_DINO = new Item(new FabricItemSettings().food(FoodComponents.COOKED_BEEF).group(Main.ITEM_GROUP));
    public static final Item SYRUP_BOTTLE = new SyrupBottleItem(new FabricItemSettings().food(new FoodComponent.Builder().hunger(5).saturationModifier(0.8F).build()).group(Main.ITEM_GROUP).maxCount(16));
    public static final Item SHROOM_SHAKE = new ShroomShakeItem(new FabricItemSettings().food(new FoodComponent.Builder().hunger(3).saturationModifier(0.6F).statusEffect(new StatusEffectInstance(StatusEffects.INSTANT_HEALTH, 2, 0, false, false), 1.0F).build()).group(Main.ITEM_GROUP).maxCount(16));
    public static final Item SUPER_MUSHROOM = new SuperMushroomItem(Sounds.ITEM_SUPER_MUSHROOM, new FabricItemSettings().food(new FoodComponent.Builder().alwaysEdible().statusEffect(new StatusEffectInstance(StatusEffects.INSTANT_HEALTH, 2, 0, false, false), 1.0F).build()).group(Main.ITEM_GROUP).maxCount(16));
    public static final Item GOLDEN_MUSHROOM = new SuperMushroomItem(Sounds.ITEM_SUPER_MUSHROOM, new FabricItemSettings().food(new FoodComponent.Builder().alwaysEdible().statusEffect(new StatusEffectInstance(StatusEffects.INSTANT_HEALTH, 2, 0, false, false), 1.0F).statusEffect(new StatusEffectInstance(StatusEffects.SPEED, 500, 1, false, false, true), 1.0F).build()).group(Main.ITEM_GROUP).maxCount(16));
    public static final Item ONE_UP = new SuperMushroomItem(Sounds.ITEM_ONE_UP, new FabricItemSettings().food(new FoodComponent.Builder().alwaysEdible().statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 6000, 4, false, false, true), 1.0F).build()).group(Main.ITEM_GROUP).maxCount(16).rarity(Rarity.UNCOMMON));
    public static final Item LIFE_MUSHROOM = new SuperMushroomItem(Sounds.ITEM_ONE_UP, new FabricItemSettings().food(new FoodComponent.Builder().alwaysEdible().statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 6000, 4, false, false, true), 1.0F).build()).group(Main.ITEM_GROUP).maxCount(1).rarity(Rarity.RARE));
    public static final Item POISON_MUSHROOM = new SuperMushroomItem(Sounds.ITEM_POISON_MUSHROOM, new FabricItemSettings().food(new FoodComponent.Builder().alwaysEdible().statusEffect(new StatusEffectInstance(StatusEffects.POISON, 1000, 1), 1.0F).build()).group(Main.ITEM_GROUP).maxCount(16));
    public static final Item FIRE_FLOWER = new FireFlowerItem(new FabricItemSettings().maxDamage(48).group(Main.ITEM_GROUP));
    public static final Item ICE_FLOWER = new IceFlowerItem(new FabricItemSettings().maxDamage(32).group(Main.ITEM_GROUP));
    public static final Item BOOMERANG_FLOWER = new BoomerangFlowerItem(new FabricItemSettings().maxDamage(48).group(Main.ITEM_GROUP));
    public static final Item GOLD_FLOWER = new GoldFlowerItem(new FabricItemSettings().maxDamage(24).rarity(Rarity.UNCOMMON).group(Main.ITEM_GROUP));
    public static final Item MAGIC_WAND = new MagicWandItem(new FabricItemSettings().maxDamage(24).group(Main.ITEM_GROUP));
    public static final Item MAGIC_PAINTBRUSH = new MagicPaintbrushItem(new FabricItemSettings().maxDamage(24).group(Main.ITEM_GROUP));
    public static final Item BEE_MUSHROOM = new PowerUpItem(PowerUp.BEE, Sounds.ENTITY_GENERIC_POWER_UP, new FabricItemSettings().maxCount(16).group(Main.ITEM_GROUP));
    public static final Item SUPER_LEAF = new PowerUpItem(PowerUp.TANOOKI, Sounds.ENTITY_GENERIC_TRANSFORM, new FabricItemSettings().maxCount(16).group(Main.ITEM_GROUP));
    public static final Item SUPER_BELL = new PowerUpItem(PowerUp.CAT, Sounds.ENTITY_GENERIC_POWER_UP, new FabricItemSettings().maxCount(16).group(Main.ITEM_GROUP));
    public static final Item SUPER_STAR = new SuperStarItem(new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(16).rarity(Rarity.UNCOMMON));
    public static final Item HAMMER = new HammerItem(new FabricItemSettings().maxCount(16).group(Main.ITEM_GROUP));
    public static final Item TURNIP = new TurnipItem(new FabricItemSettings().maxCount(16).group(Main.ITEM_GROUP));
    public static final Item BOMB = new BombItem(new FabricItemSettings().maxCount(16).group(Main.ITEM_GROUP));
    public static final Item SUPER_HEART = new SuperHeartItem(new FabricItemSettings().rarity(Rarity.UNCOMMON).maxCount(16).group(Main.ITEM_GROUP));
    public static final Item SUPER_PICKAX = new BlockItem(ModBlocks.SUPER_PICKAX, new FabricItemSettings().rarity(Rarity.RARE).maxDamage(50).group(Main.ITEM_GROUP));
    public static final Item GO_KART = new GoKartItem(new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(1));
    public static final Item DRY_BONES_SHELL = new DryBonesShellItem(new FabricItemSettings().group(Main.ITEM_GROUP).fireproof().maxCount(1));
    public static final Item DRY_BONES_PILE = new BlockItem(ModBlocks.DRY_BONES_PILE, new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(16));
    public static final Item TRAMPOLINE_MINECART = new MinecartItem(EnumAddons.TRAMPOLINE, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item AMANITA_BOAT = new BoatItem(false, EnumAddons.AMANITA_BOAT, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item AMANITA_CHEST_BOAT = new BoatItem(true, EnumAddons.AMANITA_BOAT, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item DARK_AMANITA_BOAT = new BoatItem(false, EnumAddons.DARK_AMANITA_BOAT, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item DARK_AMANITA_CHEST_BOAT = new BoatItem(true, EnumAddons.DARK_AMANITA_BOAT, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item BELL_BOAT = new BoatItem(false, EnumAddons.BELL_BOAT, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item BELL_CHEST_BOAT = new BoatItem(true, EnumAddons.BELL_BOAT, new FabricItemSettings().maxCount(1).group(Main.ITEM_GROUP));
    public static final Item GREEN_MUSHROOM_ON_A_STICK = new OnAStickItem<>(new FabricItemSettings().maxDamage(100).group(Main.ITEM_GROUP), ModEntities.BUZZY_BEETLE, 1);
    public static final Item WARP_LINK = new WarpLinkItem(new FabricItemSettings().group(Main.ITEM_GROUP).maxDamage(64));
    public static final Item FUZZY_MAGNET = new FuzzyMagnetItem(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item LAUNCH_STAR = new LaunchStarItem(new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.RARE));
    public static final Item MECHAKOOPA = new MechakoopaItem(new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item GOO_ME = new GooMeItem(new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(16));
    public static final Item MUSIC_DISC_FIRE_FACTORY = new MusicDiscItem(1, Sounds.MUSIC_BOSS_1, new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(1).rarity(Rarity.RARE), 60) {};
    public static final Item MUSIC_DISC_TOXICITY = new MusicDiscItem(10, Sounds.MUSIC_DISC_TOXICITY, new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(1).rarity(Rarity.RARE), 133) {};
    public static final Item MUSIC_DISC_WALTZ_OF_THE_LOST = new MusicDiscItem(11, Sounds.MUSIC_DISC_WALTZ_OF_THE_LOST, new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(1).rarity(Rarity.RARE), 115) {};
    public static final Item MUSIC_DISC_MY_SONG = new MusicDiscItem(13, Sounds.MUSIC_DISC_MY_SONG, new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(1).rarity(Rarity.RARE), 72) {};
    public static final Item MUSIC_DISC_TRAPPED = new MusicDiscItem(0, Sounds.MUSIC_DISC_TRAPPED, new FabricItemSettings().group(Main.ITEM_GROUP).maxCount(1).rarity(Rarity.EPIC), 109) {};
    public static final Item ARROW_STAMP = new StampItem(StampEntity.Stamp.ARROW, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item BLOOPER_STAMP = new StampItem(StampEntity.Stamp.BLOOPER, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item BOO_STAMP = new StampItem(StampEntity.Stamp.BOO, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item BUZZY_STAMP = new StampItem(StampEntity.Stamp.BUZZY, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item CAT_STAMP = new StampItem(StampEntity.Stamp.CAT, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item CLOUD_STAMP = new StampItem(StampEntity.Stamp.CLOUD, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item FISH_STAMP = new StampItem(StampEntity.Stamp.FISH, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item FLOWER_STAMP = new StampItem(StampEntity.Stamp.FLOWER, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item FUZZY_STAMP = new StampItem(StampEntity.Stamp.FUZZY, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item GOOMBA_STAMP = new StampItem(StampEntity.Stamp.GOOMBA, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item GRAFFITI_STAMP = new StampItem(StampEntity.Stamp.GRAFFITI, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item LUIGI_STAMP = new StampItem(StampEntity.Stamp.LUIGI, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item MARIO_STAMP = new StampItem(StampEntity.Stamp.MARIO, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item MOM_STAMP = new StampItem(StampEntity.Stamp.MOM, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item MUSHROOM_STAMP = new StampItem(StampEntity.Stamp.MUSHROOM, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item PRINCESS_STAMP = new StampItem(StampEntity.Stamp.PRINCESS, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item SMILEY_STAMP = new StampItem(StampEntity.Stamp.SMILEY, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item ZOMBIE_STAMP = new StampItem(StampEntity.Stamp.ZOMBIE, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    private static final ArmorMaterial JUMP_ARMOR = new JumpArmorMaterial();
    public static final Item JUMP_BOOTS = new JumpBootsItem(JUMP_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    public static final Item PLUMBER_CAP = new PlumberCapItem(JUMP_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial PRINCESS_ARMOR = new PrincessArmorMaterial();
    public static final Item PRINCESS_CROWN = new ArmorItem(PRINCESS_ARMOR, EquipmentSlot.HEAD, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial CLOUD_ARMOR = new CloudArmorMaterial();
    public static final Item CLOUD_BOOTS = new CloudBootsItem(CLOUD_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial GREEN_SHELL_ARMOR = new GreenShellArmorMaterial();
    public static final Item GREEN_SHELL = new ShellItem(0, GREEN_SHELL_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial RED_SHELL_ARMOR = new RedShellArmorMaterial();
    public static final Item RED_SHELL = new ShellItem(1, RED_SHELL_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial BLUE_SHELL_ARMOR = new BlueShellArmorMaterial();
    public static final Item BLUE_SHELL = new ShellItem(2, BLUE_SHELL_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial GOLD_SHELL_ARMOR = new GoldShellArmorMaterial();
    public static final Item GOLD_SHELL = new ShellItem(3, GOLD_SHELL_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial BUZZY_SHELL_ARMOR = new BuzzyArmorMaterial();
    public static final Item BUZZY_SHELL = new ShellItem(-1, BUZZY_SHELL_ARMOR, new FabricItemSettings().group(Main.ITEM_GROUP));
    private static final ArmorMaterial SHY_GUY_ARMOR = new ShyGuyArmorMaterial();
    public static final Item SHY_GUY_MASK = new ArmorItem(SHY_GUY_ARMOR, EquipmentSlot.HEAD, new FabricItemSettings().group(Main.ITEM_GROUP));

    private static void registerItem(String name, Item item) {
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, name), item);
    }

    private static void registerItem(float compost, String name, Item item) {
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, name), item);
        CompostingChanceRegistry.INSTANCE.add(item, compost);
    }

    public static void register() {
        registerItem("warp_frame", new BlockItem(ModBlocks.WARP_FRAME, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("corrupted_warp_frame", new BlockItem(ModBlocks.CORRUPTED_WARP_FRAME, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bowser_lock", new BlockItem(ModBlocks.BOWSER_LOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("empty_block", new BlockItem(ModBlocks.EMPTY_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("question_block", new BlockItem(ModBlocks.QUESTION_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("exclamation_block", new BlockItem(ModBlocks.EXCLAMATION_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("fake_block", new BlockItem(ModBlocks.FAKE_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("glow_block", new BlockItem(ModBlocks.GLOW_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dash_block", new BlockItem(ModBlocks.DASH_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("pull_block", new BlockItem(ModBlocks.PULL_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("propeller_block", new BlockItem(ModBlocks.PROPELLER_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bill_blaster", new BlockItem(ModBlocks.BILL_BLASTER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("spike_trap", new BlockItem(ModBlocks.SPIKE_TRAP, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("on_off_switch", new BlockItem(ModBlocks.ON_OFF_SWITCH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dotted_line_block", new BlockItem(ModBlocks.DOTTED_LINE_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("red_dotted_line_block", new BlockItem(ModBlocks.RED_DOTTED_LINE_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("pow_block", new BlockItem(ModBlocks.POW_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("p_switch", new BlockItem(ModBlocks.P_SWITCH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("super_pickax", SUPER_PICKAX);
        registerItem("stone_torch", new BlockItem(ModBlocks.STONE_TORCH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chincho_torch", new BlockItem(ModBlocks.CHINCHO_TORCH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("boo_lantern", new BlockItem(ModBlocks.BOO_LANTERN, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("girder", new BlockItem(ModBlocks.GIRDER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("donut_block", new BlockItem(ModBlocks.DONUT_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("jump_block", new BlockItem(ModBlocks.JUMP_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("trampoline", new BlockItem(ModBlocks.TRAMPOLINE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("redstone_trampoline", new BlockItem(ModBlocks.REDSTONE_TRAMPOLINE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("question_box", new BlockItem(ModBlocks.QUESTION_BOX, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("raw_bronze_block", new BlockItem(ModBlocks.RAW_BRONZE_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bronze_block", new BlockItem(ModBlocks.BRONZE_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bronze_slab", new BlockItem(ModBlocks.BRONZE_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bronze_stairs", new BlockItem(ModBlocks.BRONZE_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("white_bronze", new BlockItem(ModBlocks.WHITE_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("orange_bronze", new BlockItem(ModBlocks.ORANGE_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("magenta_bronze", new BlockItem(ModBlocks.MAGENTA_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_blue_bronze", new BlockItem(ModBlocks.LIGHT_BLUE_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("yellow_bronze", new BlockItem(ModBlocks.YELLOW_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lime_bronze", new BlockItem(ModBlocks.LIME_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("pink_bronze", new BlockItem(ModBlocks.PINK_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gray_bronze", new BlockItem(ModBlocks.GRAY_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_gray_bronze", new BlockItem(ModBlocks.LIGHT_GRAY_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cyan_bronze", new BlockItem(ModBlocks.CYAN_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("purple_bronze", new BlockItem(ModBlocks.PURPLE_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blue_bronze", new BlockItem(ModBlocks.BLUE_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("brown_bronze", new BlockItem(ModBlocks.BROWN_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("green_bronze", new BlockItem(ModBlocks.GREEN_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("red_bronze", new BlockItem(ModBlocks.RED_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("black_bronze", new BlockItem(ModBlocks.BLACK_BRONZE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstool_soil", new BlockItem(ModBlocks.TOADSTOOL_SOIL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("coarse_toadstool_soil", new BlockItem(ModBlocks.COARSE_TOADSTOOL_SOIL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstool_grass", new BlockItem(ModBlocks.TOADSTOOL_GRASS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstool_path", new BlockItem(ModBlocks.TOADSTOOL_PATH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.5f,"toadstool_turf", new BlockItem(ModBlocks.TOADSTOOL_TURF, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("grassy_toadstone", new BlockItem(ModBlocks.GRASSY_TOADSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("grassy_hardstone", new BlockItem(ModBlocks.GRASSY_HARDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cherry_soil", new BlockItem(ModBlocks.CHERRY_SOIL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cherry_grass", new BlockItem(ModBlocks.CHERRY_GRASS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chocolate_ground", new BlockItem(ModBlocks.CHOCOLATE_GROUND, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_chocolate_ground", new BlockItem(ModBlocks.DARK_CHOCOLATE_GROUND, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("smooth_chocolate_ground", new BlockItem(ModBlocks.SMOOTH_CHOCOLATE_GROUND, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("sherbet_soil", new BlockItem(ModBlocks.SHERBET_SOIL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("snowy_sherbet_soil", new BlockItem(ModBlocks.SNOWY_SHERBET_SOIL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("sherbet_bricks", new BlockItem(ModBlocks.SHERBET_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("sherbet_brick_slab", new BlockItem(ModBlocks.SHERBET_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("sherbet_brick_stairs", new BlockItem(ModBlocks.SHERBET_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("sherbet_brick_wall", new BlockItem(ModBlocks.SHERBET_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("shoresand", new BlockItem(ModBlocks.SHORESAND, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("shoregrass", new BlockItem(ModBlocks.SHOREGRASS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gritzy_sand", new BlockItem(ModBlocks.GRITZY_SAND, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("quicksand", new BlockItem(ModBlocks.QUICKSAND, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gritzy_sandstone", new BlockItem(ModBlocks.GRITZY_SANDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("smooth_gritzy_sandstone", new BlockItem(ModBlocks.SMOOTH_GRITZY_SANDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cut_gritzy_sandstone", new BlockItem(ModBlocks.CUT_GRITZY_SANDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_gritzy_sandstone", new BlockItem(ModBlocks.CHISELED_GRITZY_SANDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gritzy_sandstone_slab", new BlockItem(ModBlocks.GRITZY_SANDSTONE_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gritzy_sandstone_stairs", new BlockItem(ModBlocks.GRITZY_SANDSTONE_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gritzy_sandstone_wall", new BlockItem(ModBlocks.GRITZY_SANDSTONE_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("shroomstone", new BlockItem(ModBlocks.SHROOMSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cobbled_shroomstone", new BlockItem(ModBlocks.COBBLED_SHROOMSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("exposed_shroomstone", new BlockItem(ModBlocks.EXPOSED_SHROOMSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("charrock", new BlockItem(ModBlocks.CHARROCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_ore", new BlockItem(ModBlocks.CERISE_ORE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blazing_charrock", new BlockItem(ModBlocks.BLAZING_CHARROCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("goop_block", new BlockItem(ModBlocks.GOOP_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("goop", new BlockItem(ModBlocks.GOOP, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("black_paint_block", new BlockItem(ModBlocks.BLACK_PAINT_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("black_paint", new BlockItem(ModBlocks.BLACK_PAINT, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cloud_block", new BlockItem(ModBlocks.CLOUD_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("happy_cloud", new BlockItem(ModBlocks.HAPPY_CLOUD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cloud_slab", new BlockItem(ModBlocks.CLOUD_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cloud_stairs", new BlockItem(ModBlocks.CLOUD_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("rainbow_tiles", new BlockItem(ModBlocks.RAINBOW_TILES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("rainbow_tile_slab", new BlockItem(ModBlocks.RAINBOW_TILE_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("rainbow_tile_stairs", new BlockItem(ModBlocks.RAINBOW_TILE_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("rainbow_tile_wall", new BlockItem(ModBlocks.RAINBOW_TILE_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dreamwool", new BlockItem(ModBlocks.DREAMWOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dreamwool_carpet", new BlockItem(ModBlocks.DREAMWOOL_CARPET, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstone", new BlockItem(ModBlocks.TOADSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("smooth_toadstone", new BlockItem(ModBlocks.SMOOTH_TOADSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstone_bricks", new BlockItem(ModBlocks.TOADSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_toadstone_bricks", new BlockItem(ModBlocks.CHISELED_TOADSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstone_brick_slab", new BlockItem(ModBlocks.TOADSTONE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstone_brick_stairs", new BlockItem(ModBlocks.TOADSTONE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toadstone_brick_wall", new BlockItem(ModBlocks.TOADSTONE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gloomstone", new BlockItem(ModBlocks.GLOOMSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("smooth_gloomstone", new BlockItem(ModBlocks.SMOOTH_GLOOMSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gloomstone_bricks", new BlockItem(ModBlocks.GLOOMSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_gloomstone_bricks", new BlockItem(ModBlocks.CHISELED_GLOOMSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gloomstone_brick_slab", new BlockItem(ModBlocks.GLOOMSTONE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gloomstone_brick_stairs", new BlockItem(ModBlocks.GLOOMSTONE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gloomstone_brick_wall", new BlockItem(ModBlocks.GLOOMSTONE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("seastone", new BlockItem(ModBlocks.SEASTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("seastone_bricks", new BlockItem(ModBlocks.SEASTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_seastone_bricks", new BlockItem(ModBlocks.CHISELED_SEASTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("seastone_brick_slab", new BlockItem(ModBlocks.SEASTONE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("seastone_brick_stairs", new BlockItem(ModBlocks.SEASTONE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("seastone_brick_wall", new BlockItem(ModBlocks.SEASTONE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone", new BlockItem(ModBlocks.HARDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_slab", new BlockItem(ModBlocks.HARDSTONE_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_stairs", new BlockItem(ModBlocks.HARDSTONE_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("polished_hardstone", new BlockItem(ModBlocks.POLISHED_HARDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_pillar", new BlockItem(ModBlocks.HARDSTONE_PILLAR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_hardstone", new BlockItem(ModBlocks.CHISELED_HARDSTONE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("polished_hardstone_slab", new BlockItem(ModBlocks.POLISHED_HARDSTONE_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("polished_hardstone_stairs", new BlockItem(ModBlocks.POLISHED_HARDSTONE_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_bricks", new BlockItem(ModBlocks.HARDSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_hardstone_bricks", new BlockItem(ModBlocks.CHISELED_HARDSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cracked_hardstone_bricks", new BlockItem(ModBlocks.CRACKED_HARDSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("mossy_hardstone_bricks", new BlockItem(ModBlocks.MOSSY_HARDSTONE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_brick_slab", new BlockItem(ModBlocks.HARDSTONE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_brick_stairs", new BlockItem(ModBlocks.HARDSTONE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hardstone_brick_wall", new BlockItem(ModBlocks.HARDSTONE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("royalite", new BlockItem(ModBlocks.ROYALITE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("smooth_royalite", new BlockItem(ModBlocks.SMOOTH_ROYALITE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("royalite_bricks", new BlockItem(ModBlocks.ROYALITE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("chiseled_royalite_bricks", new BlockItem(ModBlocks.CHISELED_ROYALITE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cracked_royalite_bricks", new BlockItem(ModBlocks.CRACKED_ROYALITE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("royalite_brick_slab", new BlockItem(ModBlocks.ROYALITE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("royalite_brick_stairs", new BlockItem(ModBlocks.ROYALITE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("royalite_brick_wall", new BlockItem(ModBlocks.ROYALITE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_block", new BlockItem(ModBlocks.CERISE_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_bricks", new BlockItem(ModBlocks.CERISE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_tiles", new BlockItem(ModBlocks.CERISE_TILES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_brick_slab", new BlockItem(ModBlocks.CERISE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_brick_stairs", new BlockItem(ModBlocks.CERISE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_brick_wall", new BlockItem(ModBlocks.CERISE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_tile_slab", new BlockItem(ModBlocks.CERISE_TILE_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_tile_stairs", new BlockItem(ModBlocks.CERISE_TILE_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cerise_tile_wall", new BlockItem(ModBlocks.CERISE_TILE_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("golden_bricks", new BlockItem(ModBlocks.GOLDEN_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("golden_tiles", new BlockItem(ModBlocks.GOLDEN_TILES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("golden_brick_slab", new BlockItem(ModBlocks.GOLDEN_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("golden_brick_stairs", new BlockItem(ModBlocks.GOLDEN_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("golden_brick_wall", new BlockItem(ModBlocks.GOLDEN_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("crystal_bricks", new BlockItem(ModBlocks.CRYSTAL_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("crystal_brick_slab", new BlockItem(ModBlocks.CRYSTAL_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("crystal_brick_stairs", new BlockItem(ModBlocks.CRYSTAL_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("crystal_brick_wall", new BlockItem(ModBlocks.CRYSTAL_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate", new BlockItem(ModBlocks.VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bronze_ore", new BlockItem(ModBlocks.BRONZE_ORE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("topped_vanillate", new BlockItem(ModBlocks.TOPPED_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("coal_topped_vanillate", new BlockItem(ModBlocks.COAL_TOPPED_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("iron_topped_vanillate", new BlockItem(ModBlocks.IRON_TOPPED_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gold_topped_vanillate", new BlockItem(ModBlocks.GOLD_TOPPED_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amethyst_topped_vanillate", new BlockItem(ModBlocks.AMETHYST_TOPPED_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate_crumble", new BlockItem(ModBlocks.VANILLATE_CRUMBLE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate_bricks", new BlockItem(ModBlocks.VANILLATE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cracked_vanillate_bricks", new BlockItem(ModBlocks.CRACKED_VANILLATE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate_tiles", new BlockItem(ModBlocks.VANILLATE_TILES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate_brick_slab", new BlockItem(ModBlocks.VANILLATE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate_brick_stairs", new BlockItem(ModBlocks.VANILLATE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("vanillate_brick_wall", new BlockItem(ModBlocks.VANILLATE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate", new BlockItem(ModBlocks.FROSTY_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosted_vanillate", new BlockItem(ModBlocks.FROSTED_VANILLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate_crumble", new BlockItem(ModBlocks.FROSTY_VANILLATE_CRUMBLE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate_bricks", new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate_tiles", new BlockItem(ModBlocks.FROSTY_VANILLATE_TILES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate_brick_slab", new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICK_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate_brick_stairs", new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICK_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frosty_vanillate_brick_wall", new BlockItem(ModBlocks.FROSTY_VANILLATE_BRICK_WALL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_log", new BlockItem(ModBlocks.AMANITA_LOG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_wood", new BlockItem(ModBlocks.AMANITA_WOOD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stripped_amanita_log", new BlockItem(ModBlocks.STRIPPED_AMANITA_LOG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stripped_amanita_wood", new BlockItem(ModBlocks.STRIPPED_AMANITA_WOOD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_planks", new BlockItem(ModBlocks.AMANITA_PLANKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_slab", new BlockItem(ModBlocks.AMANITA_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_stairs", new BlockItem(ModBlocks.AMANITA_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_sign", new SignItem(new FabricItemSettings().group(Main.ITEM_GROUP), ModBlocks.AMANITA_SIGN, ModBlocks.AMANITA_WALL_SIGN));
        registerItem("amanita_door", new BlockItem(ModBlocks.AMANITA_DOOR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_trapdoor", new BlockItem(ModBlocks.AMANITA_TRAPDOOR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_fence", new BlockItem(ModBlocks.AMANITA_FENCE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_fence_gate", new BlockItem(ModBlocks.AMANITA_FENCE_GATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_button", new BlockItem(ModBlocks.AMANITA_BUTTON, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("amanita_pressure_plate", new BlockItem(ModBlocks.AMANITA_PRESSURE_PLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"amanita_leaves", new BlockItem(ModBlocks.AMANITA_LEAVES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"fruiting_amanita_leaves", new BlockItem(ModBlocks.FRUITING_AMANITA_LEAVES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_log", new BlockItem(ModBlocks.DARK_AMANITA_LOG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_wood", new BlockItem(ModBlocks.DARK_AMANITA_WOOD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stripped_dark_amanita_log", new BlockItem(ModBlocks.STRIPPED_DARK_AMANITA_LOG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stripped_dark_amanita_wood", new BlockItem(ModBlocks.STRIPPED_DARK_AMANITA_WOOD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_planks", new BlockItem(ModBlocks.DARK_AMANITA_PLANKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_slab", new BlockItem(ModBlocks.DARK_AMANITA_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_stairs", new BlockItem(ModBlocks.DARK_AMANITA_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_sign", new SignItem(new FabricItemSettings().group(Main.ITEM_GROUP), ModBlocks.DARK_AMANITA_SIGN, ModBlocks.DARK_AMANITA_WALL_SIGN));
        registerItem("dark_amanita_door", new BlockItem(ModBlocks.DARK_AMANITA_DOOR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_trapdoor", new BlockItem(ModBlocks.DARK_AMANITA_TRAPDOOR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_fence", new BlockItem(ModBlocks.DARK_AMANITA_FENCE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_fence_gate", new BlockItem(ModBlocks.DARK_AMANITA_FENCE_GATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_button", new BlockItem(ModBlocks.DARK_AMANITA_BUTTON, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_amanita_pressure_plate", new BlockItem(ModBlocks.DARK_AMANITA_PRESSURE_PLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "dark_amanita_leaves", new BlockItem(ModBlocks.DARK_AMANITA_LEAVES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "fruiting_dark_amanita_leaves", new BlockItem(ModBlocks.FRUITING_DARK_AMANITA_LEAVES, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_log", new BlockItem(ModBlocks.BELL_LOG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_wood", new BlockItem(ModBlocks.BELL_WOOD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stripped_bell_log", new BlockItem(ModBlocks.STRIPPED_BELL_LOG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stripped_bell_wood", new BlockItem(ModBlocks.STRIPPED_BELL_WOOD, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_planks", new BlockItem(ModBlocks.BELL_PLANKS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_slab", new BlockItem(ModBlocks.BELL_SLAB, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_stairs", new BlockItem(ModBlocks.BELL_STAIRS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_sign", new SignItem(new FabricItemSettings().group(Main.ITEM_GROUP), ModBlocks.BELL_SIGN, ModBlocks.BELL_WALL_SIGN));
        registerItem("bell_door", new BlockItem(ModBlocks.BELL_DOOR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_trapdoor", new BlockItem(ModBlocks.BELL_TRAPDOOR, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_fence", new BlockItem(ModBlocks.BELL_FENCE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_fence_gate", new BlockItem(ModBlocks.BELL_FENCE_GATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_button", new BlockItem(ModBlocks.BELL_BUTTON, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bell_pressure_plate", new BlockItem(ModBlocks.BELL_PRESSURE_PLATE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "bell_cap", new BlockItem(ModBlocks.BELL_CAP, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "darkened_bell_cap", new BlockItem(ModBlocks.DARKENED_BELL_CAP, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"brown_toad_stool", new BlockItem(ModBlocks.BROWN_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"red_toad_stool", new BlockItem(ModBlocks.RED_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"green_toad_stool", new BlockItem(ModBlocks.GREEN_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"yellow_toad_stool", new BlockItem(ModBlocks.YELLOW_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"purple_toad_stool", new BlockItem(ModBlocks.PURPLE_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"orange_toad_stool", new BlockItem(ModBlocks.ORANGE_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"pink_toad_stool", new BlockItem(ModBlocks.PINK_TOAD_STOOL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.85f,"green_mushroom_block", new BlockItem(ModBlocks.GREEN_MUSHROOM_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.85f,"yellow_mushroom_block", new BlockItem(ModBlocks.YELLOW_MUSHROOM_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.85f,"purple_mushroom_block", new BlockItem(ModBlocks.PURPLE_MUSHROOM_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.85f,"orange_mushroom_block", new BlockItem(ModBlocks.ORANGE_MUSHROOM_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.85f,"pink_mushroom_block", new BlockItem(ModBlocks.PINK_MUSHROOM_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"beanstalk_block", new BlockItem(ModBlocks.BEANSTALK_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("strawberry_coral_block", new BlockItem(ModBlocks.STRAWBERRY_CORAL_BLOCK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("jellybeam", new BlockItem(ModBlocks.JELLYBEAM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("frozen_muncher", new BlockItem(ModBlocks.FROZEN_MUNCHER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("freezie", new BlockItem(ModBlocks.FREEZIE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("star_cluster", new BlockItem(ModBlocks.STAR_CLUSTER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("star_panel", new BlockItem(ModBlocks.STAR_PANEL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("yoshi_egg", new BlockItem(ModBlocks.YOSHI_EGG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lil_oink_egg", new BlockItem(ModBlocks.LIL_OINK_EGG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_gray_dreamplush", new BlockItem(ModBlocks.LIGHT_GRAY_DREAMPLUSH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("brown_dreamplush", new BlockItem(ModBlocks.BROWN_DREAMPLUSH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("white_warp_pipe", new BlockItem(ModBlocks.WHITE_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("orange_warp_pipe", new BlockItem(ModBlocks.ORANGE_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("magenta_warp_pipe", new BlockItem(ModBlocks.MAGENTA_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_blue_warp_pipe", new BlockItem(ModBlocks.LIGHT_BLUE_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("yellow_warp_pipe", new BlockItem(ModBlocks.YELLOW_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lime_warp_pipe", new BlockItem(ModBlocks.LIME_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("pink_warp_pipe", new BlockItem(ModBlocks.PINK_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gray_warp_pipe", new BlockItem(ModBlocks.GRAY_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_gray_warp_pipe", new BlockItem(ModBlocks.LIGHT_GRAY_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cyan_warp_pipe", new BlockItem(ModBlocks.CYAN_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("purple_warp_pipe", new BlockItem(ModBlocks.PURPLE_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blue_warp_pipe", new BlockItem(ModBlocks.BLUE_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("brown_warp_pipe", new BlockItem(ModBlocks.BROWN_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("green_warp_pipe", new BlockItem(ModBlocks.GREEN_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("red_warp_pipe", new BlockItem(ModBlocks.RED_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("black_warp_pipe", new BlockItem(ModBlocks.BLACK_WARP_PIPE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("white_pipe_body", new BlockItem(ModBlocks.WHITE_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("orange_pipe_body", new BlockItem(ModBlocks.ORANGE_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("magenta_pipe_body", new BlockItem(ModBlocks.MAGENTA_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_blue_pipe_body", new BlockItem(ModBlocks.LIGHT_BLUE_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("yellow_pipe_body", new BlockItem(ModBlocks.YELLOW_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lime_pipe_body", new BlockItem(ModBlocks.LIME_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("pink_pipe_body", new BlockItem(ModBlocks.PINK_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gray_pipe_body", new BlockItem(ModBlocks.GRAY_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_gray_pipe_body", new BlockItem(ModBlocks.LIGHT_GRAY_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cyan_pipe_body", new BlockItem(ModBlocks.CYAN_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("purple_pipe_body", new BlockItem(ModBlocks.PURPLE_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blue_pipe_body", new BlockItem(ModBlocks.BLUE_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("brown_pipe_body", new BlockItem(ModBlocks.BROWN_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("green_pipe_body", new BlockItem(ModBlocks.GREEN_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("red_pipe_body", new BlockItem(ModBlocks.RED_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("black_pipe_body", new BlockItem(ModBlocks.BLACK_PIPE_BODY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("flagpole", new BlockItem(ModBlocks.FLAGPOLE, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("white_flag", new BlockItem(ModBlocks.WHITE_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("orange_flag", new BlockItem(ModBlocks.ORANGE_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("magenta_flag", new BlockItem(ModBlocks.MAGENTA_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_blue_flag", new BlockItem(ModBlocks.LIGHT_BLUE_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("yellow_flag", new BlockItem(ModBlocks.YELLOW_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lime_flag", new BlockItem(ModBlocks.LIME_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("pink_flag", new BlockItem(ModBlocks.PINK_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("gray_flag", new BlockItem(ModBlocks.GRAY_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("light_gray_flag", new BlockItem(ModBlocks.LIGHT_GRAY_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cyan_flag", new BlockItem(ModBlocks.CYAN_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("purple_flag", new BlockItem(ModBlocks.PURPLE_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blue_flag", new BlockItem(ModBlocks.BLUE_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("brown_flag", new BlockItem(ModBlocks.BROWN_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("green_flag", new BlockItem(ModBlocks.GREEN_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("red_flag", new BlockItem(ModBlocks.RED_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("black_flag", new BlockItem(ModBlocks.BLACK_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("rainbow_flag", new BlockItem(ModBlocks.RAINBOW_FLAG, new FabricItemSettings().group(Main.ITEM_GROUP).rarity(Rarity.RARE)));
        registerItem("short_grass", new BlockItem(ModBlocks.SHORT_GRASS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"red_grass", new BlockItem(ModBlocks.RED_GRASS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"bush", new BlockItem(ModBlocks.BUSH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.5f,"horsetail", new BlockItem(ModBlocks.HORSETAIL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cave_mushrooms", new BlockItem(ModBlocks.CAVE_MUSHROOMS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blue_cave_mushrooms", new BlockItem(ModBlocks.BLUE_CAVE_MUSHROOMS, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"green_mushroom", new BlockItem(ModBlocks.GREEN_MUSHROOM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"yellow_mushroom", new BlockItem(ModBlocks.YELLOW_MUSHROOM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"purple_mushroom", new BlockItem(ModBlocks.PURPLE_MUSHROOM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"orange_mushroom", new BlockItem(ModBlocks.ORANGE_MUSHROOM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"pink_mushroom", new BlockItem(ModBlocks.PINK_MUSHROOM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"yellow_songflower", new BlockItem(ModBlocks.YELLOW_SONGFLOWER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"blue_songflower", new BlockItem(ModBlocks.BLUE_SONGFLOWER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"pink_songflower", new BlockItem(ModBlocks.PINK_SONGFLOWER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"rocket_flower", new PlaceableOnWaterItem(ModBlocks.ROCKET_FLOWER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"pawflower", new BlockItem(ModBlocks.PAWFLOWER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"fire_tulip", new BlockItem(ModBlocks.FIRE_TULIP, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "yellow_flowerbed", new BlockItem(ModBlocks.YELLOW_FLOWERBED, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "white_flowerbed", new BlockItem(ModBlocks.WHITE_FLOWERBED, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "amanita_carpet", new BlockItem(ModBlocks.AMANITA_CARPET, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"amanita_sapling", new BlockItem(ModBlocks.AMANITA_SAPLING, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"dark_amanita_sapling", new BlockItem(ModBlocks.DARK_AMANITA_SAPLING, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f,"bell_sapling", new BlockItem(ModBlocks.BELL_SAPLING, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.5f,"smiley_stem", new BlockItem(ModBlocks.SMILEY_STEM, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.65f,"smiley_sunflower", new BlockItem(ModBlocks.SMILEY_SUNFLOWER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.5f,"beanstalk", new BlockItem(ModBlocks.BEANSTALK, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("muncher", new BlockItem(ModBlocks.MUNCHER, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "pit_plant", new BlockItem(ModBlocks.PIT_PLANT, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem(0.3f, "piranha_lily", new PlaceableOnWaterItem(ModBlocks.PIRANHA_LILY, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("fuzzbush", new BlockItem(ModBlocks.FUZZBUSH, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("strawberry_coral", new BlockItem(ModBlocks.STRAWBERRY_CORAL, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("raw_bronze", RAW_BRONZE);
        registerItem("bronze_ingot", BRONZE_INGOT);
        registerItem("cerise", CERISE);
        registerItem("coin", COIN);
        registerItem("star_coin", STAR_COIN);
        registerItem("stellar_shard", STELLAR_SHARD);
        registerItem("yellow_star_bit", YELLOW_STAR_BIT);
        registerItem("green_star_bit", GREEN_STAR_BIT);
        registerItem("blue_star_bit", BLUE_STAR_BIT);
        registerItem("purple_star_bit", PURPLE_STAR_BIT);
        registerItem(0.3f,"smiley_sunflower_seed", SMILEY_SUNFLOWER_SEED);
        registerItem("spindrift_blossom", SPINDRIFT_BLOSSOM);
        registerItem("kart_tire", KART_TIRE);
        registerItem("spike", SPIKE);
        registerItem("troop_hide", TROOP_HIDE);
        registerItem("cloud_puff", CLOUD_PUFF);
        registerItem("subcon_thread", SUBCON_THREAD);
        registerItem("goop_ball", GOOP_BALL);
        registerItem("black_paint_ball", BLACK_PAINT);
        registerItem("fuzzball", FUZZBALL);
        registerItem("buzzy_shell_piece", BUZZY_SHELL_PIECE);
        registerItem("poison_bucket", POISON_BUCKET);
        registerItem("bottled_ghost", BOTTLED_GHOST);
        registerItem("key", KEY);
        registerItem("skeleton_key", SKELETON_KEY);
        registerItem("power_star", POWER_STAR);
        registerItem("ztar", ZTAR);
        registerItem("power_shard", POWER_SHARD);
        registerItem(0.3f,"yoshi_fruit", YOSHI_FRUIT);
        registerItem("yoshi_cookie", YOSHI_COOKIE);
        registerItem("horsetail_tart", HORSETAIL_TART);
        registerItem("raw_dino", RAW_DINO);
        registerItem("cooked_dino", COOKED_DINO);
        registerItem("syrup_bottle", SYRUP_BOTTLE);
        registerItem("shroom_shake", SHROOM_SHAKE);
        registerItem("super_mushroom", SUPER_MUSHROOM);
        registerItem("golden_mushroom", GOLDEN_MUSHROOM);
        registerItem("one_up", ONE_UP);
        registerItem("life_mushroom", LIFE_MUSHROOM);
        registerItem("poison_mushroom", POISON_MUSHROOM);
        registerItem("fire_flower", FIRE_FLOWER);
        registerItem("ice_flower", ICE_FLOWER);
        registerItem("boomerang_flower", BOOMERANG_FLOWER);
        registerItem("gold_flower", GOLD_FLOWER);
        registerItem("magic_wand", MAGIC_WAND);
        registerItem("magic_paintbrush", MAGIC_PAINTBRUSH);
        registerItem("bee_mushroom", BEE_MUSHROOM);
        registerItem("super_leaf", SUPER_LEAF);
        registerItem("super_bell", SUPER_BELL);
        registerItem("super_star", SUPER_STAR);
        registerItem("hammer", HAMMER);
        registerItem("turnip", TURNIP);
        registerItem("bomb", BOMB);
        registerItem("super_heart", SUPER_HEART);
        registerItem("green_shell", GREEN_SHELL);
        registerItem("red_shell", RED_SHELL);
        registerItem("blue_shell", BLUE_SHELL);
        registerItem("gold_shell", GOLD_SHELL);
        registerItem("buzzy_shell", BUZZY_SHELL);
        registerItem("plumber_cap", PLUMBER_CAP);
        registerItem("princess_crown", PRINCESS_CROWN);
        registerItem("shy_guy_mask", SHY_GUY_MASK);
        registerItem("jump_boots", JUMP_BOOTS);
        registerItem("cloud_boots", CLOUD_BOOTS);
        registerItem("go_kart", GO_KART);
        registerItem("trampoline_minecart", TRAMPOLINE_MINECART);
        registerItem("dry_bones_pile", DRY_BONES_PILE);
        registerItem("dry_bones_shell", DRY_BONES_SHELL);
        registerItem("amanita_boat", AMANITA_BOAT);
        registerItem("amanita_chest_boat", AMANITA_CHEST_BOAT);
        registerItem("dark_amanita_boat", DARK_AMANITA_BOAT);
        registerItem("dark_amanita_chest_boat", DARK_AMANITA_CHEST_BOAT);
        registerItem("bell_boat", BELL_BOAT);
        registerItem("bell_chest_boat", BELL_CHEST_BOAT);
        registerItem("green_mushroom_on_a_stick", GREEN_MUSHROOM_ON_A_STICK);
        registerItem("warp_link", WARP_LINK);
        registerItem("fuzzy_magnet", FUZZY_MAGNET);
        registerItem("launch_star", LAUNCH_STAR);
        registerItem("mechakoopa", MECHAKOOPA);
        registerItem("goo_me", GOO_ME);
        registerItem("music_disc_fire_factory", MUSIC_DISC_FIRE_FACTORY);
        registerItem("music_disc_toxicity", MUSIC_DISC_TOXICITY);
        registerItem("music_disc_waltz_of_the_lost", MUSIC_DISC_WALTZ_OF_THE_LOST);
        registerItem("music_disc_my_song", MUSIC_DISC_MY_SONG);
        registerItem("music_disc_trapped", MUSIC_DISC_TRAPPED);
        registerItem("arrow_stamp", ARROW_STAMP);
        registerItem("blooper_stamp", BLOOPER_STAMP);
        registerItem("boo_stamp", BOO_STAMP);
        registerItem("buzzy_stamp", BUZZY_STAMP);
        registerItem("cat_stamp", CAT_STAMP);
        registerItem("cloud_stamp", CLOUD_STAMP);
        registerItem("fish_stamp", FISH_STAMP);
        registerItem("flower_stamp", FLOWER_STAMP);
        registerItem("fuzzy_stamp", FUZZY_STAMP);
        registerItem("goomba_stamp", GOOMBA_STAMP);
        registerItem("graffiti_stamp", GRAFFITI_STAMP);
        registerItem("luigi_stamp", LUIGI_STAMP);
        registerItem("mario_stamp", MARIO_STAMP);
        registerItem("mom_stamp", MOM_STAMP);
        registerItem("mushroom_stamp", MUSHROOM_STAMP);
        registerItem("princess_stamp", PRINCESS_STAMP);
        registerItem("smiley_stamp", SMILEY_STAMP);
        registerItem("zombie_stamp", ZOMBIE_STAMP);
        registerItem("petey_piranha_spawn_egg", new SpawnEggItem(ModEntities.PETEY_PIRANHA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("king_bob_omb_spawn_egg", new SpawnEggItem(ModEntities.KING_BOB_OMB, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("king_boo_spawn_egg", new SpawnEggItem(ModEntities.KING_BOO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("toad_spawn_egg", new SpawnEggItem(ModEntities.TOAD, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("mailtoad_spawn_egg", new SpawnEggItem(ModEntities.MAILTOAD, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("goomba_spawn_egg", new SpawnEggItem(ModEntities.GOOMBA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("paragoomba_spawn_egg", new SpawnEggItem(ModEntities.PARAGOOMBA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("koopa_troopa_spawn_egg", new SpawnEggItem(ModEntities.KOOPA_TROOPA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("paratroopa_spawn_egg", new SpawnEggItem(ModEntities.PARATROOPA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("piranha_plant_spawn_egg", new SpawnEggItem(ModEntities.PIRANHA_PLANT, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("putrid_piranha_spawn_egg", new SpawnEggItem(ModEntities.PUTRID_PIRANHA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blooper_spawn_egg", new SpawnEggItem(ModEntities.BLOOPER, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("cheep_cheep_spawn_egg", new SpawnEggItem(ModEntities.CHEEP_CHEEP, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lava_bubble_spawn_egg", new SpawnEggItem(ModEntities.LAVA_BUBBLE, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("hammer_bro_spawn_egg", new SpawnEggItem(ModEntities.HAMMER_BRO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("fire_bro_spawn_egg", new SpawnEggItem(ModEntities.FIRE_BRO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("ice_bro_spawn_egg", new SpawnEggItem(ModEntities.ICE_BRO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("spiny_spawn_egg", new SpawnEggItem(ModEntities.SPINY, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("buzzy_beetle_spawn_egg", new SpawnEggItem(ModEntities.BUZZY_BEETLE, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bullet_bill_spawn_egg", new SpawnEggItem(ModEntities.BULLET_BILL, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("shy_guy_spawn_egg", new SpawnEggItem(ModEntities.SHY_GUY, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        //pokey
        registerItem("bob_omb_spawn_egg", new SpawnEggItem(ModEntities.BOB_OMB, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dry_bones_spawn_egg", new SpawnEggItem(ModEntities.DRY_BONES, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("parabones_spawn_egg", new SpawnEggItem(ModEntities.PARABONES, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("thwomp_spawn_egg", new SpawnEggItem(ModEntities.THWOMP, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("boo_spawn_egg", new SpawnEggItem(ModEntities.BOO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("yoshi_spawn_egg", new SpawnEggItem(ModEntities.YOSHI, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("spike_top_spawn_egg", new SpawnEggItem(ModEntities.SPIKE_TOP, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("fuzzy_spawn_egg", new SpawnEggItem(ModEntities.FUZZY, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dino_rhino_spawn_egg", new SpawnEggItem(ModEntities.DINO_RHINO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("bob_omb_buddy_spawn_egg", new SpawnEggItem(ModEntities.BOB_OMB_BUDDY, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("unagi_spawn_egg", new SpawnEggItem(ModEntities.UNAGI, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("spindrift_spawn_egg", new SpawnEggItem(ModEntities.SPINDRIFT, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("moo_moo_spawn_egg", new SpawnEggItem(ModEntities.MOO_MOO, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("lil_oink_spawn_egg", new SpawnEggItem(ModEntities.LIL_OINK, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("sleepy_sheep_spawn_egg", new SpawnEggItem(ModEntities.SLEEPY_SHEEP, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("glad_goomba_spawn_egg", new SpawnEggItem(ModEntities.GLAD_GOOMBA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("glad_paragoomba_spawn_egg", new SpawnEggItem(ModEntities.GLAD_PARAGOOMBA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_goomba_spawn_egg", new SpawnEggItem(ModEntities.DARK_GOOMBA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("dark_paragoomba_spawn_egg", new SpawnEggItem(ModEntities.DARK_PARAGOOMBA, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("fake_block_spawn_egg", new SpawnEggItem(ModEntities.FAKE_BLOCK, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("stingby_spawn_egg", new SpawnEggItem(ModEntities.STINGBY, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("blockstepper_spawn_egg", new SpawnEggItem(ModEntities.BLOCKSTEPPER, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("mummy_me_spawn_egg", new SpawnEggItem(ModEntities.MUMMY_ME, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("mud_trooper_spawn_egg", new SpawnEggItem(ModEntities.MUD_TROOPER, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("rotten_mushroom_spawn_egg", new SpawnEggItem(ModEntities.ROTTEN_MUSHROOM, 16777215, 16777215, new FabricItemSettings().group(Main.ITEM_GROUP)));
        registerItem("forager_spawn_egg", new SpawnEggItem(ModEntities.FORAGER, 0x959B9B, 0xac3232, new FabricItemSettings().group(Main.ITEM_GROUP)));
    }
}
